Header updates
utkdigitalinitiatives/exhibits pull request #20
Opened 2021-08-12 15:17 UTC by sfunk3

**JIRA Issue**: [EXHIBIT-75](https://jirautk.atlassian.net/browse/EXHIBIT-75) & [EXHIBIT-76](https://jirautk.atlassian.net/browse/EXHIBIT-76)

What does this do?
==================

Following the Galston tech meeting on 8/10, I've made several adjustments to responsive styles for header (logo, libraries links) and navigation menu, including:

- Swapping the png logo for svg and making sure the height is brand compliant (not under 30px at the smallest)
- Adding links for account, search, and home. These are just links to those resources, including search. Mark and I discussed this as MVP for this project, so feedback would be appreciated.
- Setting breakpoints and corresponding responsive styles for mobile views (e.g. the header as a whole is a lot tighter going from tablet size down, the hover underline on menu items no longer stretches to 100% on mobile views, etc)

How should this be reviewed?
============================

Checkout the `header-updates` branch and test the site header at different breakpoints to make sure responsiveness is up to par. Review to decide if we're all agreed on what's included and how it's implemented.

Additional notes:
=================

Please request changes if needed. I plan to organize the sass structure a bit better but wanted to get eyes on the changes.

2021-08-12 22:42 UTC, markpbaggett commented
@sfunk3 This seems fine to me, but I'll wait to see if @mathewjordan has feedback before merge.

2021-08-12 22:43 UTC, markpbaggett approved these changes
@sfunk3 this seems fine to me, but i'll wait on feedback from @mathewjordan before merge.

2021-08-13 14:04 UTC, mathewjordan requested changes
Edit - Delete this as a submitting prematurely.

2021-08-13 14:10 UTC, mathewjordan requested changes
@sfunk3 A few things. 

- **Responsiveness and Sass structure** - I think this isn't quite there responsively. At smaller viewports the items do not collapse at all and instead wrap underneath eachother. I also have concerns with the redundancy of structure in each media query on `src/sass/components/header.scss`. In some cases we are using breakpoint vars `@media (max-width: $breakpoint-xs)` and in others we are using hardcoded widths `@media (max-width: 500px)`. The redundancy is also happening for many selectors for each media query. I feel like we can handle this in a much cleaner way, especially since we'll need to extend some of responsive strategy across the repo.   

![image](https://user-images.githubusercontent.com/7376450/129367126-36494635-1715-49bf-bb7f-54db04c3fcb3.png)

![image](https://user-images.githubusercontent.com/7376450/129367153-22b37de3-dc1f-4f06-92b8-1b471c46aeb8.png)

- **UniversalHeader.js**, code base wise, this is not a Yith component and should not be under  `src/components/yith`. Yith are the components that interact with IIIF manifests and render them to the screen. I think this should move to `src/components`.

- There are some smaller things but I'll dig into those inline.

2021-08-13 14:10 UTC, mathewjordan commented on src/sass/components/header.scss
> +  }
This type of thing will affect all `<svg>` elements in the virtual DOM. We don't want to do that. What svg is it? can we wrap it or give it a class?

2021-08-13 14:10 UTC, mathewjordan commented on src/components/yith/UniversalHeader.js
> +          <a href="https://utk.primo.exlibrisgroup.com/discovery/search?vid=01UTN_KNOXVILLE:01UTK&lang=en" target="_blank"><span>Search</span></a></div>
Why do we wrap this in `<div>` but not the other `<a>`'s?

2021-08-13 14:10 UTC, mathewjordan commented on src/sass/components/header.scss
> +  @media (max-width: 375px) {
Why these and the breakpoint vars?

2021-08-16 20:48 UTC, sfunk3 commented
@mathewjordan I think this is in a good place for another quick review when you have a chance.

2021-08-17 14:15 UTC, mathewjordan reviewed
@sfunk3 The revamp of the responsive media queries look great.

I'm not suggesting any changes but I do have one question. Is the scope of this PR to make the header fully responsive? As it is now, I would not say that the header row is collapsing as expected. Do we address this here? or in another issue?

![image](https://user-images.githubusercontent.com/7376450/129742403-cd4b9432-9c18-4e0e-af7f-e28ee8d97b17.png)

2021-08-18 13:33 UTC, sfunk3 commented
@mat Thanks for reviewing. My thinking is that we merge these changes in and address updates separately.

2021-08-18 13:35 UTC, mathewjordan approved these changes
Sounds good @sfunk3

2021-08-18 13:35 UTC, merged